name: "CI with Github Actions"
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JAVA 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'
      - name: Checking Test Cases
        run: ./gradlew runReleaseUnitTest
      - name: Assemble Release
        run: ./gradlew assembleRelease

